services:
  - type: web
    name: srcv2-django-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python3 -m devgagan
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
